version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=devuser
      - DB_PASSWORD=devpass
      - DB_NAME=devdb
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - python_jango_course_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=devdb

volumes:
  python_jango_course_db: